server:
   port: 8085

spring: 
  datasource:
     url: jdbc:postgresql://localhost:5433/payment
     username: postgres
     password: admin
     driver-class-name: org.postgresql.Driver

     jpa: 
       hibernate:
          ddl-auto: create
       database: postgresql
       database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka: 
     bootstrap-servers: localhost:9094
     consumer:
        bootstrap-servers: localhost:9094
        group-id: myGroup
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
           spring.json.trusted.packages:  '*'